language: python
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    packages:
    - libgmp-dev
    - libmpfr-dev
before_install:
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
  - tar xzvf mpc-1.0.3.tar.gz
  - pushd mpc-1.0.3
  - ./configure
  - make
  - sudo make install
  - popd
  - export LD_LIBRARY_PATH=/usr/local/lib
install:
  - pip install gmpy2
script:
  - python setup.py test
